name: Docker Image CI

on:
  push:
    branches: [ "master" ]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  IMAGE_NAME: barry2abdulrahim/arm-arch
  IMAGE_TAG: latest

jobs:

  build_arm_job:
    name: Build and push multi-arch image
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1


    - name: Build image 
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ env.IMAGE_NAME }}
        tags: ${{ env.IMAGE_TAG }}
        archs: arm64
        dockerfiles: |
          ./simple_api/Dockerfile

    - name: Login to Docker Hub
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Docker Push
      run: docker push barry2abdulrahim/arm-arch:latest