name: Docker Image CI

on:
  push:
    branches: [ "master" ]

env:
  IMAGE_NAME: barry2abdulrahim/arm-arch
  IMAGE_TAG: v0.0.0
  IMAGE_REGISTRY: docker.io
  

jobs:

  build_arm_job:
    name: Build and push multi-arch image
    runs-on: ubuntu-20.04

    steps:
    # - uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1


    - name: Build image 
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ env.IMAGE_NAME }}
        tags: ${{ env.IMAGE_TAG }}
        archs: arm64, amd64
        dockerfiles: |
          ./simple_api/Dockerfile

    - name: Push To docker.io
      id: push-to-quay
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: ${{ env.IMAGE_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}