name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build_arm_job:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get the output
        # Echo the `uname` output parameter from the `runcmd` step
        run: pwd
    # - name: Build the Docker image
    #   run: docker build . --file student-list/simple_api/Dockerfile --tag barry2abdulrahim/arm:$(date +%s)
