name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build_arm_job:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2.1.0
    - uses: uraimo/run-on-arch-action@v2
      name: Run commands
        id: runcmd
        with:
          arch: armv7
          distro: ubuntu18.04

    - name: Login to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Build the Docker image
      run: docker build . --file $GITHUB_WORKSPACE/simple_api/Dockerfile --tag barry2abdulrahim/arm:latest

    - name: Docker Push
      run: docker push barry2abdulrahim/arm:latest
    
    - name: Get the output
        # Echo the `uname` output parameter from the `runcmd` step
        run: |
          echo "The uname output was ${{ steps.runcmd.outputs.uname }}"