name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build_arm_job:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get the output
      run: pwd
    - name: ls
      run: ls /home/runner/work/student-list/student-list

    # - name: Build the Docker image
    #   run: docker build . --file student-list/simple_api/Dockerfile --tag barry2abdulrahim/arm:$(date +%s)
